### ISSUE TITLE
Implement dumps (add tests and code samples)

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-ruby#101]
Since [v0.15.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0), MeiliSearch exposes a new functionality: [dumps](https://docs.meilisearch.com/references/dump.html#dumps)

This feature should be implemented in this SDK following [this specificacions](https://github.com/meilisearch/integration-guides/issues/44)

- [ ] Implement dump creation route
- [ ] Implement get dump status route
- [ ] Add tests
- [ ] Add code samples

**Comment by curquiza** [comment]
The code samples to add are:
```
post_dump_1: |-
get_dump_status_1: |-
```

**Comment by CaroFG** [comment]
Should we close this issue since the PR was merged ?

**Comment by curquiza** [comment]
Yes indeed! I should have linked this issue to your PR so that GitHub automatically closes it when the PR is merged, my bad!
Closing now then thanks to #114
