### ISSUE TITLE
Improve adding lots of documents and error handling when reaching maximum payload size

### ISSUE THREAD

**Issue by bb** [meilisearch/meilisearch-ruby#113]
I started off with indexing just a few fields of my test data running `index.add_documents(documents)` was just fine. After adding a few more fields, it broke like this:

```ruby
> index.add_documents(documents)
Errno::EPIPE: Broken pipe
from <internal:prelude>:131:in `__write_nonblock'
```

I could only guess that I reached the [maximum payload size](https://docs.meilisearch.com/guides/advanced_guides/known_limitations.html#payload-size) and indeed: `documents.to_json.length/1.megabyte` returned 12 while the default limit is 10.

I'd prefer if the client would handle the failed request more gracefully with a helpful error message.

It might even detect the problem before sending the request by checking the expected payload size against the servers configured value (not sure if this is exposed via API yet).

I was able to successfully add all documents in slices:
```ruby
documents.each_slice(100) {|d1| index.add_documents(d1) }
```

Even though I understand that it's not a good idea to serialize a complete dataset, especially in production, I wonder if adding convenience features automatic sending in chunks to the ruby client would be a good idea. What do you think?

**Comment by curquiza** [comment]
> I'd prefer if the client would handle the failed request more gracefully with a helpful error message.

Agreed! What kind of error do you suggest?

> Even though I understand that it's not a good idea to serialize a complete dataset, especially in production, I wonder if adding convenience features automatic sending in chunks to the ruby client would be a good idea.

What do you mean? Adding a `send_documents_in_slice` for example?

**Comment by bb** [comment]
> Agreed! What kind of error do you suggest?

One thing might be directly in meilisearch server instead of the library: returning e.g. `HTTP 413 Payload Too Large`. This could be caught in the client(s) and exposed to the developer similar to existing `ApiError`, `CommunicationError`, and `TimeoutError`. The name could be `PayloadTooLargeError`. 

If it will not be made available in the server, one could rescue Errno::EPIPE and e.g. check the body size in the exception handler and raise `PayloadTooLargeError` if it's larger than the max payload size. Not sure how to get the Payload Size limit via API though. Might be necessary to expose that, if we want to provide a very specific error message. Maybe a unspecific hint might be sufficient as a start.

The error message of the Exception could point to the docs and the docs could have samples to work around it:

* send in slices, as in the code snipped above
* send in slices made by active record batches (see below)
* increase payload size in server

> What do you mean? Adding a send_documents_in_slice for example?

Yes, something like this. Theoretically it could check the size of the documents and do as-big-as-possible slices. **But as said, maybe it's not a good idea.** If the documentation is good enough, I'd prefer this over a implementation which hides the issue and supports bad practices like loading all docs and then sending them.

In the [upcoming rails integration](https://roadmap.meilisearch.com/c/52-ruby-on-rails), it could work with [find_in_batches](https://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_in_batches) and thus work around this more easily and more memory efficiently than loading all and slicing later.

**Comment by curquiza** [comment]
Just realized that MeiliSearch should already send a `PayloadTooLarge` error.
See:
- https://docs.meilisearch.com/errors/#payload_too_large
- https://github.com/meilisearch/MeiliSearch/blob/aab041e6924892c181e7321d7effe1157b243d82/meilisearch-http/src/error.rs#L98
🤔 
Weird you get an `Errno::EPIPE: Broken pipe` error.

**Comment by curquiza** [comment]
Related to `send_documents_in_slice`: closed in favor of https://github.com/meilisearch/meilisearch-ruby/issues/218
