### ISSUE TITLE
Make the tests independent

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-ruby#122]
Currently, some tests depend on the previous ones, like in this file: https://github.com/meilisearch/meilisearch-ruby/blob/master/spec/meilisearch/client/indexes_spec.rb.

We should re-write the test suite to make the tests independent from the others. This would make our test suite more readable, trustable, and maintainable.

Independent tests mean that each test method begins with an empty MeiliSearch instance. We should automate the index creation at the beginning of each test.

**Comment by curquiza** [comment]
This issue is for someone liking working with rspec 💪

**Comment by jmks** [comment]
👋  I like working with RSpec 😄 

Let me give this a shot

**Comment by curquiza** [comment]
Hello @jmks 
I assign you 😬

**Comment by curquiza** [comment]
Closed by #230 and some improvements are described in #233
