### ISSUE TITLE
undefined method `compact' for Hash

### ISSUE THREAD

**Issue by xluffy** [meilisearch/meilisearch-ruby#131]
I try to test meilisearch gem with ruby 2.3.3. But I can't create a connection to MeiliSearch. It shows an error.

```
irb(main):002:0> client = MeiliSearch::Client.new('http://127.0.0.1')
NoMethodError: undefined method `compact' for {"Content-Type"=>"application/json", "X-Meili-API-Key"=>nil}:Hash
        from /Users/xluffy/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/meilisearch-0.15.0/lib/meilisearch/http_request.rb:17:in `initialize'
        from (irb):2:in `new'
        from (irb):2
        from /Users/xluffy/.rbenv/versions/2.3.3/bin/irb:11:in `<main>'
```

[`compact` is a method of Hash in Ruby 2.4.0](https://ruby-doc.org/core-2.4.0/Hash.html#method-i-compact). I checked meilisearch documents but don't see any warning about Ruby version is compatible.

This is not a big issue. But I think we could make a better experience for users. We can try two solutions:
- Update a document with compatible Ruby version + add `spec.required_ruby_version = '>= 2.4'` in gemspec file.
- Support version Ruby < 2.4

**Comment by curquiza** [comment]
Hello @xluffy!
Thanks for this feedback!
Since [Ruby 2.4 is not supported anymore](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/) I would rather not change the code to support ruby 2.4.
The first solution might be the best 🙂

Feel free to open a PR, we would be glad to review it! 😁

**Comment by xluffy** [comment]
@curquiza I try to test with ruby 2.5.0. It works well. But ruby-2.5.0 is nearing its end of life. Do you think should support this version.
