### ISSUE TITLE
Accept integer as a query parameter

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/meilisearch-ruby#157]
When I try to search with an integer instead of a string as the query parameter, I'm getting an error like the following:
`400 Bad Request - Invalid JSON: invalid type: integer `42`, expected a string`

I'd like to run: `index.search(42)` and get results instead of an error.

Algolia accepts an integer and transforms it into a string before sending the request. Check the source code [here](https://www.rubydoc.info/gems/algolia/Algolia%2FSearch%2FIndex:search)

**Comment by bidoubiwa** [comment]
Hey @CaroFG, thanks for noticing this issue! 
This should absolutely be fixed :)
