### ISSUE TITLE
MeiliSearch::Index times out

### ISSUE THREAD

**Issue by christianhellsten** [meilisearch/meilisearch-ruby#161]
MeiliSearch::Index times out when indexing a lot of data. The default timeout is 1.

The following page states that the timeout can be increased:
https://github.com/meilisearch/meilisearch-ruby/wiki/Client-Options

However, the MeiliSearch::Client does not pass the options to MeiliSearch::Index, so the default timeout and max_retries is always used:

https://github.com/meilisearch/meilisearch-ruby/blob/8d2251d51f5d4ea8b54db337071dd32d8d2f9b11/lib/meilisearch/client.rb#L90-L92

https://github.com/meilisearch/meilisearch-ruby/blob/8d2251d51f5d4ea8b54db337071dd32d8d2f9b11/lib/meilisearch/index.rb#L10-L14

**Comment by bidoubiwa** [comment]
Hello! Thanks a lot for raising this issue. Could you tell me a bit more about the context? Is it when using `add_documents` that the timeout occurs? 
Could you show me the code that raises the timeout? (or a short version of it)

**Comment by christianhellsten** [comment]
Yes, this is when adding ~100 000 documents in batches to the index:

```ruby
client = MeiliSearch::Client.new(url, 'masterKey', timeout: timeout, max_retries: max_retries)
index = client.index('x')
X.find_in_batches(batch_size: 1000) do |group|
  docs = group.map do |c|
    { id: c.id, name: c.name }
  end
  index.add_documents(docs)
end
```

You can see the changes I made to pass the options to the add_documents request here:
https://github.com/christianhellsten/meilisearch-ruby/commit/d547e67dac38f7f91a84237478ea109ba2b213e8

**Comment by bidoubiwa** [comment]
Ah yes! Good fix :) Do you want to open a PR with your solution?

**Comment by christianhellsten** [comment]
Thank you. I created a PR here:
https://github.com/meilisearch/meilisearch-ruby/pull/163

The integration test failed for some reason I haven't had the time to debug yet:

       expected MeiliSearch::TimeoutError, got #<Zlib::BufError: buffer error> with backtrace:

**Comment by curquiza** [comment]
Hello @christianhellsten! We'll try to come back as soon as possible to check your PR!
The error is related to this issue #60

**Comment by curquiza** [comment]
Closed with https://github.com/meilisearch/meilisearch-ruby/pull/188
