### ISSUE TITLE
Pass parameters using snake case

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-ruby#217]
Currently, when sending payload to MeiliSearch via this package, we use snake case:

```ruby
index.search(
  'hob',
  attributesToHighlight: ['*']
)
```

This is because the HashMap is directly sent to MeiliSearch without any transformation, and MeiliSearch only accepts camelCase.

However, using camelCase is not idiomatic in ruby. We would like make this package accepts snake case as well

```ruby
index.search(
  'hob',
  attributes_to_highlight: ['*']
)
```

An external contributor already did it on [meilisearch-rails](https://github.com/meilisearch/meilisearch-rails/pull/66), see https://github.com/meilisearch/meilisearch-rails/pull/49/files

We are open to contributions, feel free to ask any question :)

**Comment by brunoocasali** [comment]
@curquiza I could work on that :)

**Comment by curquiza** [comment]
Hello @brunoocasali! Yes, you can! Thank you 😊
