### ISSUE TITLE
Create `add_documents_in_batches` and `update_documents_in_batches` methodes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-ruby#218]
TODO
- Add `add_documents_in_batches`
```ruby
add_documents_in_batches(documents, batch_size = 1000, primary_key = nil)
```
- Add `update_documents_in_batches`
```ruby
update_documents_in_batches(documents, batch_size = 1000, primary_key = nil)
```
- Add tests

Here is an example implemented in python: https://github.com/meilisearch/meilisearch-python/pull/260/files
Following: https://github.com/meilisearch/integration-guides/issues/106

Feel free to ask any question! 😄

**Comment by abhilashkpy** [comment]
What are we supposed to perform in this good first issue?

**Comment by curquiza** [comment]
Hello!
You have to add the methods described in description of this issue.
The methods allow the users to add their documents by batch.
You have an example in a PR (linked in the description of the issue)

Is there a part you want me to explain better? 🙂

**Comment by FlamesRunner** [comment]
Is this still free? If so, this looks like something I'd like to tackle, if abhilashkpy doesn't want to take it :)

**Comment by curquiza** [comment]
Hello you can take it @FlamesRunner since abhilashkpy does not mention wanting to solve it :)

**Comment by FlamesRunner** [comment]
@curquiza Thanks! I've made a pull request and eagerly await your feedback.
