### ISSUE TITLE
Improve our test readability using the xUnit structure

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-ruby#284]
- [ ] Following the @brunoocasali comment: https://github.com/meilisearch/meilisearch-ruby/pull/273#discussion_r779113900 And following this guide http://blog.plataformatec.com.br/2014/04/improve-your-test-readability-using-the-xunit-structure/ we should update our specs according to this convention to increase the readability.
- [ ] We should improve the `context`, see https://www.betterspecs.org/#contexts

**Comment by brunoocasali** [comment]
I'm closing this since we don't want big refactorings on this repository.
