### ISSUE TITLE
Settings API - implement methods to customize the hard limits for pagination

### ISSUE THREAD

**Issue by Mcdostone** [meilisearch/meilisearch-ruby#344]
**Description**
Meilisearch v0.28.0 brings [customization of documents returned by search](https://docs.meilisearch.com/reference/api/pagination.html#get-pagination-settings).

Related to: 
- https://github.com/meilisearch/meilisearch/issues/2495
- https://github.com/meilisearch/meilisearch/issues/2368
- https://github.com/meilisearch/specifications/pull/157

 * Expose `pagination` object on `/indexes/:index_uid/settings/pagination` endpoints.
 * Add `GET/PATCH/DELETE` - `/indexes/:index_uid/settings/pagination` endpoints.

**Comment by brunoocasali** [comment]
Thanks for raising this issue @Mcdostone, I was planning to create it this week.

The v0.28 release was huge to the integrations team, so we decided to let part of the specs be implemented later, one of these parts is exactly this one, you can check the original plan here https://github.com/meilisearch/integration-guides/issues/205 (last section).

If you want to contribute, it will be really appreciated @Mcdostone 🥇
