### ISSUE TITLE
When I access "127.0.0.1:7700" from Vagrant, my CLI environment, I get an error "ERR_CONNECTION_REFUSED" and access is denied

### ISSUE THREAD

**Issue by sandonemaki** [meilisearch/meilisearch-ruby#390]
Hello.

my environment
- Virtual Box
- vagrant
- ubuntu 20.4
- ruby 3.0.4

When I access "127.0.0.1:7700" from Vagrant, my CLI environment, I get an error "ERR_CONNECTION_REFUSED" and access is denied.
I have configured Vagrant to accept port 7700.

On my Mac, when I access "127.0.0.1:7700", the attached dashboard appears in my browser.

Is the reason why I cannot access the dashboard at "127.0.0.1:7700" from Vagrant because I do not have a GUI environment?

![スクリーンショット 2022-11-10 10 37 51](https://user-images.githubusercontent.com/48534295/200979202-3fffdfd7-4304-4c4e-89e9-fc209762f3ce.png)

**Comment by sandonemaki** [comment]
SOLVED!

I should have stated the following so that vagrant can accept meilisearch.
`./meilisearch --db-path ./meilifiles --http-addr '0.0.0.0:7700'`

I was able to access it by typing the following into my browser!
`http://vagrant_IP:7700`

**Comment by brunoocasali** [comment]
I'm glad you could make it! :)
