### ISSUE TITLE
Search parametters don't accept lists of strings (and should)

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-ruby#41]
Search parameters like `attributesToRetrieve` can't handle a list of strings. You should be able to pass a list of fields, not just a single string or '*'.

## Example
```ruby
response = @index.search('the', attributesToRetrieve: ['title', 'release_date'])
```

## Failing test
<img width="1011" alt="Screenshot 2020-06-02 at 19 35 41" src="https://user-images.githubusercontent.com/10339833/83551639-e47dea00-a508-11ea-9fa8-93b9e444889a.png">

**Comment by curquiza** [comment]
Closed by #46
