### ISSUE TITLE
Deprecation warning on snake case

### ISSUE THREAD

**Issue by jason-hobbs** [meilisearch/meilisearch-ruby#477]
When running rails test:all on the latest version of meilisearch-ruby I am now getting:
Non-conforming attributes: searchableAttributes, filterableAttributes, sortableAttributes
Attributes will be expected to be snake_case in future versions of Meilisearch Ruby.

**Comment by brunoocasali** [comment]
Yes, that's correct, you have explicitly defined calls that are being made with camelCase attributes, just change them to snake_case and you'll be fine!

`searchableAttributes` => `searchable_attributes`
`filterableAttributes` => `filterable_attributes` and so on...

**Comment by jason-hobbs** [comment]
I don't see that I have those calls anywhere in my code.  Here is one of my models:

```
meilisearch do
    attribute :title
    attribute :description
    attribute :status
    attribute :comment do
      task_comments.pluck(:content)
    end
    attribute :user_name do
      user.username   
    end
    attribute :user_email do
      user.email
    end
    attribute :user_id do
      user.id
    end
    attribute :tag do
      if tag.present?
        tag.title
      end
    end
    sortable_attributes [:created_at]
    pagination max_total_hits: 500
    searchable_attributes [:user_name, :tag, :title, :description, :status, :comment, :user_email]
  end
```

**Comment by jason-hobbs** [comment]
It must be in the meilisearch-rails gem that I am also using.
