### ISSUE TITLE
Implement meilisearch's multi-search

### ISSUE THREAD

**Issue by ellnix** [meilisearch/meilisearch-ruby#489]
**Description**
Multi-search

**Other**

I saw an issue about integrating multi-search in meilisearch-rails, but I cannot find a similar feature or issue in meilisearch-ruby. See the [meilisearch issue](https://github.com/meilisearch/meilisearch/issues/3427) and the [meilisearch-rails issue](https://github.com/meilisearch/meilisearch-rails/issues/254).

**Comment by brunoocasali** [comment]
Hi @ellnix it is already implemented: https://github.com/meilisearch/meilisearch-ruby/pull/425

https://www.meilisearch.com/docs/reference/api/multi_search#perform-a-multi-search
