### ISSUE TITLE
Increase required ruby version

### ISSUE THREAD

**Issue by andre-m-dev** [meilisearch/meilisearch-ruby#514]
**Description**
Ruby 2.6 and 2.7 are already end of life. ([endoflife ruby](https://endoflife.date/ruby)) This gem should not support outdated ruby versions for compatibility and security reasons.

**Basic example**
`s.required_ruby_version = '>= 3.0.0'`

**Comment by curquiza** [comment]
Thank you @andre-m-dev 

For anyone: feel free to open a PR changing
- the CI manifest (in .github folder)
- the bors.toml file

**Comment by ellnix** [comment]
I suggested doing this recently, however I was instructed to keep supporting ruby 2.6 in the gemspec: https://github.com/meilisearch/meilisearch-ruby/issues/507#issuecomment-1850863437

I also think that if this is done, it should be tagged as a breaking change for the benefit of users who might currently be using meilisearch in ruby `2.x`.

**Comment by curquiza** [comment]
> I also think that if this is done, it should be tagged as a breaking change for the benefit of users who might currently be using meilisearch in ruby 2.x

Yes @ellnix this is something we usually do: dropping support is tagged as `breaking change` to increase the minor version of the library

**Comment by curquiza** [comment]
@brunoocasali what are the reasons to keep an old ruby version?

**Comment by curquiza** [comment]
Discussed with @brunoocasali 

We are ok to move to minimal version >= 3.0.0 👍

**Comment by andre-m-dev** [comment]
Thank you
