### ISSUE TITLE
proximity_precision not available?

### ISSUE THREAD

**Issue by mech** [meilisearch/meilisearch-ruby#518]
Hi when I try to do this, it has undefined method. Is it because the release of the main Meilisearch and the library is somewhat not aligned?

```ruby
client = MeiliSearch::Client.new("http://localhost:7700")

client.index("User").proximity_precision
```

I am following the documentation example at here: https://www.meilisearch.com/docs/reference/api/settings#example-21 where there is a Ruby example.

**Comment by ellnix** [comment]
The documentation website automatically scrapes the examples from the main branch, where this has been implemented. Unfortunately the 0.26 release does not include `proximity_precision` (see #512).
