### ISSUE TITLE
Entire index is deleted if you pass nil to delete_document

### ISSUE THREAD

**Issue by jeremylynch** [meilisearch/meilisearch-ruby#556]
There is a serious bug which occurs when you pass `nil` to `delete_document` which causes the entire index to be cleared. 

```rb
Book.index.delete_document(nil)
```

Instead, I think it would be safer to return an error when nil is passed to avoid this catastrophic outcome.

**Comment by curquiza** [comment]
Thank you for the the report @jeremylynch 

Any PR are welcome (from anyone)
