### ISSUE TITLE
Remove sys-info routes

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-ruby#72]
As stated in https://github.com/meilisearch/MeiliSearch/pull/810 and https://github.com/meilisearch/integration-guides/issues/36 the sys-info routes will be considered as deprecated in MeiliSearch v0.13.0. These routes should be removed from this SDK accordingly.

**Comment by renehernandez** [comment]
@eskombro @curquiza I am going to implement this

**Comment by curquiza** [comment]
Hello @renehernandez!
Sorry for the confusion, as @eskombro explained in your PR, it has been already implemented!
That's our fault, we should have kept the issue up-to-date.

**Comment by curquiza** [comment]
Closing the issue then since it's merged on a dev branch.
