### ISSUE TITLE
Handle new versions of meilisearch

### ISSUE THREAD

**Issue by Overload119** [meilisearch/meilisearch-ruby#91]
MeiliSearch::CommunicationError: An error occurred while trying to connect to the MeiliSearch instance: Failed to open TCP connection to 127.0.0.1:7700 (Connection refused - connect(2) for "127.0.0.1" port 7700)
  /Users/asharifr/.rvm/gems/ruby-2.7.0/gems/meilisearch-0.13.3/lib/meilisearch/http_request.rb:60:in `rescue in send_request'
  /Users/asharifr/.rvm/gems/ruby-2.7.0/gems/meilisearch-0.13.3/lib/meilisearch/http_request.rb:57:in `send_request'
  /Users/asharifr/.rvm/gems/ruby-2.7.0/gems/meilisearch-0.13.3/lib/meilisearch/http_request.rb:21:in `http_get'
  /Users/asharifr/.rvm/gems/ruby-2.7.0/gems/meilisearch-0.13.3/lib/meilisearch/client.rb:10:in `indexes'

**Comment by Overload119** [comment]
Whoops - unrelated to the gem. I was trying to load an old Meili Search database.

**Comment by curquiza** [comment]
No problem! 😉
